project_id = "fkjxgyxphbwsomockdwr"

[functions.recommend-items]
verify_jwt = false

[functions.plan-procurement]
verify_jwt = false

[functions.travel-assistant]
verify_jwt = false

[functions.transport-agent]
verify_jwt = false

[functions.search-flights]
verify_jwt = false

[functions.book-flight]
verify_jwt = false

[functions.ai-flight-agent]
verify_jwt = false

[functions.search-hotels]
verify_jwt = false

[functions.search-venues]
verify_jwt = false

[functions.search-transport]
verify_jwt = false
